# Generated by Django 2.2.1 on 2019-06-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('site', models.URLField(verbose_name='site_address')),
                ('blank', models.IntegerField(max_length=3)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=3)),
                ('serial', models.CharField(max_length=2)),
                ('number', models.IntegerField(max_length=10)),
                ('issue', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('b_day', models.DateField(verbose_name='date od birthday')),
                ('phone_number', models.CharField(max_length=250)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Passport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField(max_length=5)),
                ('departure', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('duration', models.FloatField(max_length=5)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1)),
                ('service_class', models.CharField(max_length=3)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Company')),
            ],
        ),
    ]
