# Generated by Django 2.2.1 on 2019-06-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=6)),
                ('ticket', models.IntegerField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('id_fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Fare')),
                ('id_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Flight')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.User')),
            ],
        ),
    ]
