# Generated by Django 2.2.1 on 2019-06-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'airline'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_fare',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_flight',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='fare',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tickets.Fare'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='flight',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tickets.Flight'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.User'),
        ),
    ]
