# Generated by Django 2.2.1 on 2019-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190603_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'flight'},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='tax',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('PRG', 'Прага'), ('AMS', 'Амстердам'), ('KBP', 'Борисполь'), ('VIN', 'Винница'), ('OZH', 'Запорожье'), ('CWC', 'Черновцы'), ('HRK', 'Харьков'), ('DNK', 'Днепр'), ('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('LWO', 'Львов')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('PRG', 'Прага'), ('AMS', 'Амстердам'), ('KBP', 'Борисполь'), ('VIN', 'Винница'), ('OZH', 'Запорожье'), ('CWC', 'Черновцы'), ('HRK', 'Харьков'), ('DNK', 'Днепр'), ('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('LWO', 'Львов')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(max_length=4),
        ),
    ]
