# Generated by Django 2.2.1 on 2019-06-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190603_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('KBP', 'Борисполь'), ('HRK', 'Харьков'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('LWO', 'Львов'), ('CWC', 'Черновцы'), ('IST', 'Стамбул'), ('PRG', 'Прага'), ('AMS', 'Амстердам'), ('DNK', 'Днепр'), ('BCN', 'Барселона'), ('OZH', 'Запорожье')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('KBP', 'Борисполь'), ('HRK', 'Харьков'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('LWO', 'Львов'), ('CWC', 'Черновцы'), ('IST', 'Стамбул'), ('PRG', 'Прага'), ('AMS', 'Амстердам'), ('DNK', 'Днепр'), ('BCN', 'Барселона'), ('OZH', 'Запорожье')], max_length=3, null=True),
        ),
    ]
