# Generated by Django 2.2.1 on 2019-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190604_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='cost',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('LWO', 'Львов'), ('IST', 'Стамбул'), ('CWC', 'Черновцы'), ('VIN', 'Винница'), ('DNK', 'Днепр'), ('AMS', 'Амстердам'), ('HRK', 'Харьков'), ('BCN', 'Барселона'), ('IEV', 'Жуляны'), ('PRG', 'Прага'), ('KBP', 'Борисполь'), ('KHE', 'Херсон'), ('ODS', 'Одесса'), ('OZH', 'Запорожье')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('LWO', 'Львов'), ('IST', 'Стамбул'), ('CWC', 'Черновцы'), ('VIN', 'Винница'), ('DNK', 'Днепр'), ('AMS', 'Амстердам'), ('HRK', 'Харьков'), ('BCN', 'Барселона'), ('IEV', 'Жуляны'), ('PRG', 'Прага'), ('KBP', 'Борисполь'), ('KHE', 'Херсон'), ('ODS', 'Одесса'), ('OZH', 'Запорожье')], max_length=3, null=True),
        ),
    ]
