# Generated by Django 2.2.1 on 2019-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190604_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('bus', 'business'), ('eco', 'economy'), ('low', 'lowcost')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('CWC', 'Черновцы'), ('PRG', 'Прага'), ('DNK', 'Днепр'), ('OZH', 'Запорожье'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('HRK', 'Харьков'), ('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('IST', 'Стамбул')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('CWC', 'Черновцы'), ('PRG', 'Прага'), ('DNK', 'Днепр'), ('OZH', 'Запорожье'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('HRK', 'Харьков'), ('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('IST', 'Стамбул')], max_length=3, null=True),
        ),
    ]
