# Generated by Django 2.2.1 on 2019-06-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190604_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='b_day',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('eco', 'economy'), ('low', 'lowcost'), ('bus', 'business')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('LWO', 'Львов'), ('IST', 'Стамбул'), ('DNK', 'Днепр'), ('KHE', 'Херсон'), ('KBP', 'Борисполь'), ('VIN', 'Винница'), ('CWC', 'Черновцы'), ('OZH', 'Запорожье'), ('AMS', 'Амстердам'), ('IEV', 'Жуляны'), ('HRK', 'Харьков'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('BCN', 'Барселона')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('LWO', 'Львов'), ('IST', 'Стамбул'), ('DNK', 'Днепр'), ('KHE', 'Херсон'), ('KBP', 'Борисполь'), ('VIN', 'Винница'), ('CWC', 'Черновцы'), ('OZH', 'Запорожье'), ('AMS', 'Амстердам'), ('IEV', 'Жуляны'), ('HRK', 'Харьков'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('BCN', 'Барселона')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Passport'),
        ),
    ]
