# Generated by Django 2.2.1 on 2019-06-05 12:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20190604_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='b_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('DNK', 'Днепр'), ('AMS', 'Амстердам'), ('CWC', 'Черновцы'), ('PRG', 'Прага'), ('BCN', 'Барселона'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('KHE', 'Херсон'), ('HRK', 'Харьков'), ('VIN', 'Винница'), ('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('LWO', 'Львов'), ('IST', 'Стамбул')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('DNK', 'Днепр'), ('AMS', 'Амстердам'), ('CWC', 'Черновцы'), ('PRG', 'Прага'), ('BCN', 'Барселона'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('KHE', 'Херсон'), ('HRK', 'Харьков'), ('VIN', 'Винница'), ('ODS', 'Одесса'), ('IEV', 'Жуляны'), ('LWO', 'Львов'), ('IST', 'Стамбул')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
