# Generated by Django 2.2.1 on 2019-06-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20190605_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='serial',
        ),
        migrations.AddField(
            model_name='passport',
            name='p_number',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('PRG', 'Прага'), ('KHE', 'Херсон'), ('DNK', 'Днепр'), ('ODS', 'Одесса'), ('OZH', 'Запорожье'), ('CWC', 'Черновцы'), ('AMS', 'Амстердам'), ('KBP', 'Борисполь'), ('BCN', 'Барселона'), ('VIN', 'Винница'), ('IST', 'Стамбул'), ('LWO', 'Львов'), ('HRK', 'Харьков'), ('IEV', 'Жуляны')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('PRG', 'Прага'), ('KHE', 'Херсон'), ('DNK', 'Днепр'), ('ODS', 'Одесса'), ('OZH', 'Запорожье'), ('CWC', 'Черновцы'), ('AMS', 'Амстердам'), ('KBP', 'Борисполь'), ('BCN', 'Барселона'), ('VIN', 'Винница'), ('IST', 'Стамбул'), ('LWO', 'Львов'), ('HRK', 'Харьков'), ('IEV', 'Жуляны')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tickets.User'),
        ),
    ]
