# Generated by Django 2.2.1 on 2019-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20190605_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('low', 'lowcost'), ('bus', 'business'), ('eco', 'economy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('CWC', 'Черновцы'), ('DNK', 'Днепр'), ('LWO', 'Львов'), ('OZH', 'Запорожье'), ('PRG', 'Прага'), ('KHE', 'Херсон'), ('IST', 'Стамбул'), ('AMS', 'Амстердам'), ('ODS', 'Одесса'), ('KBP', 'Борисполь'), ('BCN', 'Барселона'), ('VIN', 'Винница'), ('IEV', 'Жуляны')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('CWC', 'Черновцы'), ('DNK', 'Днепр'), ('LWO', 'Львов'), ('OZH', 'Запорожье'), ('PRG', 'Прага'), ('KHE', 'Херсон'), ('IST', 'Стамбул'), ('AMS', 'Амстердам'), ('ODS', 'Одесса'), ('KBP', 'Борисполь'), ('BCN', 'Барселона'), ('VIN', 'Винница'), ('IEV', 'Жуляны')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='p_number',
            field=models.CharField(blank=True, default=None, max_length=250, unique=True),
        ),
    ]
