# Generated by Django 2.2.1 on 2019-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20190605_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('bus', 'business'), ('low', 'lowcost'), ('eco', 'economy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('KHE', 'Херсон'), ('IEV', 'Жуляны'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('IST', 'Стамбул'), ('VIN', 'Винница'), ('OZH', 'Запорожье'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('HRK', 'Харьков'), ('ODS', 'Одесса'), ('CWC', 'Черновцы')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('KHE', 'Херсон'), ('IEV', 'Жуляны'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('IST', 'Стамбул'), ('VIN', 'Винница'), ('OZH', 'Запорожье'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('HRK', 'Харьков'), ('ODS', 'Одесса'), ('CWC', 'Черновцы')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='p_number',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
