# Generated by Django 2.2.1 on 2019-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20190605_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('bus', 'business'), ('eco', 'economy'), ('low', 'lowcost')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('IEV', 'Жуляны'), ('ODS', 'Одесса'), ('VIN', 'Винница'), ('CWC', 'Черновцы'), ('AMS', 'Амстердам'), ('OZH', 'Запорожье'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('IST', 'Стамбул'), ('KHE', 'Херсон'), ('BCN', 'Барселона')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('IEV', 'Жуляны'), ('ODS', 'Одесса'), ('VIN', 'Винница'), ('CWC', 'Черновцы'), ('AMS', 'Амстердам'), ('OZH', 'Запорожье'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('IST', 'Стамбул'), ('KHE', 'Херсон'), ('BCN', 'Барселона')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='p_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
