# Generated by Django 2.2.1 on 2019-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20190605_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('low', 'lowcost'), ('bus', 'business'), ('eco', 'economy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('IEV', 'Жуляны'), ('AMS', 'Амстердам'), ('LWO', 'Львов'), ('IST', 'Стамбул'), ('BCN', 'Барселона'), ('HRK', 'Харьков'), ('ODS', 'Одесса'), ('CWC', 'Черновцы'), ('OZH', 'Запорожье'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('PRG', 'Прага'), ('DNK', 'Днепр'), ('KBP', 'Борисполь')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('IEV', 'Жуляны'), ('AMS', 'Амстердам'), ('LWO', 'Львов'), ('IST', 'Стамбул'), ('BCN', 'Барселона'), ('HRK', 'Харьков'), ('ODS', 'Одесса'), ('CWC', 'Черновцы'), ('OZH', 'Запорожье'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('PRG', 'Прага'), ('DNK', 'Днепр'), ('KBP', 'Борисполь')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='p_number',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
