# Generated by Django 2.2.1 on 2019-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20190605_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('LWO', 'Львов'), ('DNK', 'Днепр'), ('OZH', 'Запорожье'), ('VIN', 'Винница'), ('KHE', 'Херсон'), ('BCN', 'Барселона'), ('ODS', 'Одесса'), ('IST', 'Стамбул'), ('KBP', 'Борисполь'), ('PRG', 'Прага'), ('IEV', 'Жуляны'), ('AMS', 'Амстердам'), ('CWC', 'Черновцы')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('LWO', 'Львов'), ('DNK', 'Днепр'), ('OZH', 'Запорожье'), ('VIN', 'Винница'), ('KHE', 'Херсон'), ('BCN', 'Барселона'), ('ODS', 'Одесса'), ('IST', 'Стамбул'), ('KBP', 'Борисполь'), ('PRG', 'Прага'), ('IEV', 'Жуляны'), ('AMS', 'Амстердам'), ('CWC', 'Черновцы')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='passport',
            name='p_number',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
