# Generated by Django 2.2.1 on 2019-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20190605_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('bus', 'business'), ('low', 'lowcost'), ('eco', 'economy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('KBP', 'Борисполь'), ('IEV', 'Жуляны'), ('BCN', 'Барселона'), ('LWO', 'Львов'), ('CWC', 'Черновцы'), ('OZH', 'Запорожье'), ('VIN', 'Винница'), ('PRG', 'Прага'), ('AMS', 'Амстердам'), ('IST', 'Стамбул'), ('KHE', 'Херсон'), ('DNK', 'Днепр'), ('ODS', 'Одесса')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('HRK', 'Харьков'), ('KBP', 'Борисполь'), ('IEV', 'Жуляны'), ('BCN', 'Барселона'), ('LWO', 'Львов'), ('CWC', 'Черновцы'), ('OZH', 'Запорожье'), ('VIN', 'Винница'), ('PRG', 'Прага'), ('AMS', 'Амстердам'), ('IST', 'Стамбул'), ('KHE', 'Херсон'), ('DNK', 'Днепр'), ('ODS', 'Одесса')], max_length=3, null=True),
        ),
    ]
