# Generated by Django 2.2.1 on 2019-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20190605_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('eco', 'economy'), ('low', 'lowcost'), ('bus', 'business')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('IST', 'Стамбул'), ('VIN', 'Винница'), ('KHE', 'Херсон'), ('HRK', 'Харьков'), ('KBP', 'Борисполь'), ('LWO', 'Львов'), ('CWC', 'Черновцы'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('OZH', 'Запорожье'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('IEV', 'Жуляны')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('IST', 'Стамбул'), ('VIN', 'Винница'), ('KHE', 'Херсон'), ('HRK', 'Харьков'), ('KBP', 'Борисполь'), ('LWO', 'Львов'), ('CWC', 'Черновцы'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('OZH', 'Запорожье'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('IEV', 'Жуляны')], max_length=3, null=True),
        ),
    ]
