# Generated by Django 2.2.1 on 2019-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20190605_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='serial',
        ),
        migrations.AddField(
            model_name='passport',
            name='p_number',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('low', 'lowcost'), ('eco', 'economy'), ('bus', 'business')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('IST', 'Стамбул'), ('CWC', 'Черновцы'), ('KBP', 'Борисполь'), ('OZH', 'Запорожье'), ('AMS', 'Амстердам'), ('KHE', 'Херсон'), ('PRG', 'Прага'), ('LWO', 'Львов'), ('VIN', 'Винница'), ('BCN', 'Барселона'), ('ODS', 'Одесса'), ('HRK', 'Харьков'), ('DNK', 'Днепр'), ('IEV', 'Жуляны')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('IST', 'Стамбул'), ('CWC', 'Черновцы'), ('KBP', 'Борисполь'), ('OZH', 'Запорожье'), ('AMS', 'Амстердам'), ('KHE', 'Херсон'), ('PRG', 'Прага'), ('LWO', 'Львов'), ('VIN', 'Винница'), ('BCN', 'Барселона'), ('ODS', 'Одесса'), ('HRK', 'Харьков'), ('DNK', 'Днепр'), ('IEV', 'Жуляны')], max_length=3, null=True),
        ),
    ]
