# Generated by Django 2.2.1 on 2019-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_auto_20190605_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='expity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('eco', 'economy'), ('bus', 'business'), ('low', 'lowcost')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('IST', 'Стамбул'), ('OZH', 'Запорожье'), ('LWO', 'Львов'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('CWC', 'Черновцы'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('KBP', 'Борисполь'), ('VIN', 'Винница'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('DNK', 'Днепр'), ('HRK', 'Харьков')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('IST', 'Стамбул'), ('OZH', 'Запорожье'), ('LWO', 'Львов'), ('AMS', 'Амстердам'), ('BCN', 'Барселона'), ('CWC', 'Черновцы'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('KBP', 'Борисполь'), ('VIN', 'Винница'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('DNK', 'Днепр'), ('HRK', 'Харьков')], max_length=3, null=True),
        ),
    ]
