# Generated by Django 2.2.1 on 2019-06-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_auto_20190605_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('low', 'lowcost'), ('bus', 'business'), ('eco', 'economy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('BCN', 'Барселона'), ('IST', 'Стамбул'), ('ODS', 'Одесса'), ('HRK', 'Харьков'), ('OZH', 'Запорожье'), ('CWC', 'Черновцы'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('DNK', 'Днепр'), ('IEV', 'Жуляны'), ('PRG', 'Прага'), ('AMS', 'Амстердам')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('BCN', 'Барселона'), ('IST', 'Стамбул'), ('ODS', 'Одесса'), ('HRK', 'Харьков'), ('OZH', 'Запорожье'), ('CWC', 'Черновцы'), ('KHE', 'Херсон'), ('VIN', 'Винница'), ('LWO', 'Львов'), ('KBP', 'Борисполь'), ('DNK', 'Днепр'), ('IEV', 'Жуляны'), ('PRG', 'Прага'), ('AMS', 'Амстердам')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Passport'),
        ),
    ]
