# Generated by Django 2.2.1 on 2019-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20190605_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('low', 'lowcost'), ('eco', 'economy'), ('bus', 'business')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('KHE', 'Херсон'), ('CWC', 'Черновцы'), ('IST', 'Стамбул'), ('KBP', 'Борисполь'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('BCN', 'Барселона'), ('IEV', 'Жуляны'), ('LWO', 'Львов'), ('OZH', 'Запорожье'), ('VIN', 'Винница'), ('AMS', 'Амстердам'), ('ODS', 'Одесса'), ('HRK', 'Харьков')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('KHE', 'Херсон'), ('CWC', 'Черновцы'), ('IST', 'Стамбул'), ('KBP', 'Борисполь'), ('DNK', 'Днепр'), ('PRG', 'Прага'), ('BCN', 'Барселона'), ('IEV', 'Жуляны'), ('LWO', 'Львов'), ('OZH', 'Запорожье'), ('VIN', 'Винница'), ('AMS', 'Амстердам'), ('ODS', 'Одесса'), ('HRK', 'Харьков')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
