# Generated by Django 2.2.1 on 2019-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_auto_20190605_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('eco', 'economy'), ('low', 'lowcost'), ('bus', 'business')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('PRG', 'Прага'), ('HRK', 'Харьков'), ('LWO', 'Львов'), ('ODS', 'Одесса'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('CWC', 'Черновцы'), ('AMS', 'Амстердам'), ('KHE', 'Херсон'), ('IEV', 'Жуляны'), ('VIN', 'Винница'), ('BCN', 'Барселона'), ('DNK', 'Днепр'), ('IST', 'Стамбул')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('PRG', 'Прага'), ('HRK', 'Харьков'), ('LWO', 'Львов'), ('ODS', 'Одесса'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('CWC', 'Черновцы'), ('AMS', 'Амстердам'), ('KHE', 'Херсон'), ('IEV', 'Жуляны'), ('VIN', 'Винница'), ('BCN', 'Барселона'), ('DNK', 'Днепр'), ('IST', 'Стамбул')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket',
            field=models.IntegerField(max_length=10),
        ),
    ]
