# Generated by Django 2.2.1 on 2019-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_auto_20190605_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('low', 'lowcost'), ('eco', 'economy'), ('bus', 'business')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('DNK', 'Днепр'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('LWO', 'Львов'), ('AMS', 'Амстердам'), ('VIN', 'Винница'), ('HRK', 'Харьков'), ('PRG', 'Прага'), ('IST', 'Стамбул'), ('KHE', 'Херсон'), ('CWC', 'Черновцы'), ('ODS', 'Одесса'), ('BCN', 'Барселона'), ('IEV', 'Жуляны')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('DNK', 'Днепр'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('LWO', 'Львов'), ('AMS', 'Амстердам'), ('VIN', 'Винница'), ('HRK', 'Харьков'), ('PRG', 'Прага'), ('IST', 'Стамбул'), ('KHE', 'Херсон'), ('CWC', 'Черновцы'), ('ODS', 'Одесса'), ('BCN', 'Барселона'), ('IEV', 'Жуляны')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
