# Generated by Django 2.2.1 on 2019-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_auto_20190605_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare',
            name='service_class',
            field=models.CharField(choices=[('bus', 'business'), ('low', 'lowcost'), ('eco', 'economy')], max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(choices=[('VIN', 'Винница'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('AMS', 'Амстердам'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('CWC', 'Черновцы'), ('HRK', 'Харьков'), ('BCN', 'Барселона'), ('IST', 'Стамбул'), ('LWO', 'Львов'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('DNK', 'Днепр')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('VIN', 'Винница'), ('PRG', 'Прага'), ('ODS', 'Одесса'), ('AMS', 'Амстердам'), ('IEV', 'Жуляны'), ('KHE', 'Херсон'), ('CWC', 'Черновцы'), ('HRK', 'Харьков'), ('BCN', 'Барселона'), ('IST', 'Стамбул'), ('LWO', 'Львов'), ('OZH', 'Запорожье'), ('KBP', 'Борисполь'), ('DNK', 'Днепр')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
